###post user
POST http://localhost:2121/users
Content-Type: application/json

{
    "name": "Hunter biden"
}

###post comment
POST http://localhost:2121/comments
Content-Type: application/json

{
    "content": "Cogito Ergo Sum"
}